### ISSUE TITLE
error "exec /opt/oddslingers.poker/bin/entrypoint.sh: no such file or directory"

### ISSUE THREAD

**Issue by tgeels** [Monadical-SAS/oddslingers.poker#7]
Why am I getting this error when the file exists:(
error "exec /opt/oddslingers.poker/bin/entrypoint.sh: no such file or directory"

**Comment by afreydev** [comment]
@tgeels 
How are you trying to execute Oddslingers?
Are you using Windows?

**Comment by 1itt1eB0y** [comment]
same issue, on WSL2 and Windows11 Pro

**Comment by afreydev** [comment]
@1itt1eB0y 
could you give us more details about the steps you are doing please?

**Comment by 1itt1eB0y** [comment]
> @1itt1eB0y could you give us more details about the steps you are doing please?

I only tried `docker-compose.yml`, the `prod` and `beta` versions did not

it will raise this error when run `django_base` image (i can attach a screenshot when i get home if you need)

just run the commands below
```bash
git clone https://github.com/monadical-sas/oddslingers.poker.git
cd oddslingers.poker

docker-compose run django ./manage.py migrate
docker-compose run django ./manage.py createsuperuser
docker-compose up
```

and i tried to build all the image first
```bash
docker-compose build
docker-compose run django ./manage.py migrate
docker-compose run django ./manage.py createsuperuser
docker-compose up
```

**Comment by afreydev** [comment]
@1itt1eB0y 
sure. When you have a chance please attach the image.
I ran the platform without problems today. So I appreciate the screenshots.

![image](https://github.com/Monadical-SAS/oddslingers.poker/assets/43050896/d9ca129a-e9aa-4d4b-8f99-a3f4411f9faa)

**Comment by 1itt1eB0y** [comment]
`docker image inspect oddslingers:django_base`
```yaml
[
    {
        "Id": "sha256:a39906e5f89c6fce82839cdd188b464bb3962f308fab50a54fc258fbf44fca4c",
        "RepoTags": [
            "oddslingers:django_base"
        ],
        "RepoDigests": [],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2024-03-16T07:56:54.110781128Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/opt/oddslingers.poker/.venv-docker/bin:/opt/oddslingers.poker/bin:./node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D",
                "PYTHON_VERSION=3.7.17",
                "PYTHON_PIP_VERSION=23.0.1",
                "PYTHON_SETUPTOOLS_VERSION=57.5.0",
                "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/0d8570dc44796f4369b652222cf176b3db6ac70e/public/get-pip.py",
                "PYTHON_GET_PIP_SHA256=96461deced5c2a487ddc65207ec5a9cffeca0d34e7af7ea1afc470ff0d746207",
                "ODDSLINGERS_ROOT=/opt/oddslingers.poker",
                "DATA_DIR=/opt/oddslingers.poker/data",
                "HTTP_PORT=8000",
                "DJANGO_USER=www-data",
                "VENV_NAME=.venv-docker",
                "NODE_MAJOR=18",
                "LC_ALL=C.UTF-8",
                "PYTHONDONTWRITEBYTECODE=1",
                "PYTHONUNBUFFERED=1"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/opt/oddslingers.poker",
            "Entrypoint": [
                "/opt/oddslingers.poker/bin/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.project": "oddslingerspoker",
                "com.docker.compose.service": "django",
                "com.docker.compose.version": "2.24.6"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 1641092152,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/baj9e5lsj1eefhvzsfo2m29sd/diff:/var/lib/docker/overlay2/io4rkw3u6ohaxrarexe6ohyv9/diff:/var/lib/docker/overlay2/ih9v24ut04rcx6dklf7fl3src/diff:/var/lib/docker/overlay2/4kg188pexitttz74iqz7esxzz/diff:/var/lib/docker/overlay2/kl7d10yxhwa5rcsvujiwn6cp5/diff:/var/lib/docker/overlay2/2f4tog51x94hzhfh0n4gs5xrs/diff:/var/lib/docker/overlay2/hw7lt0jk0kd7vtlo2mj344hno/diff:/var/lib/docker/overlay2/yp8vrwpm680vkqaknb4ib7znd/diff:/var/lib/docker/overlay2/s9ylywldli9hpp5nxrkyxuloy/diff:/var/lib/docker/overlay2/xf28nnrha38x95zrdl17g0q1o/diff:/var/lib/docker/overlay2/om8wctzfznzfpalf4fqx29gn0/diff:/var/lib/docker/overlay2/ypu0gy1uz5ucj7dpzz6etir79/diff:/var/lib/docker/overlay2/7sg13ngxrq3kyw73lybzo4s0b/diff:/var/lib/docker/overlay2/y9tz1dxgiow6tmznf1nldcha1/diff:/var/lib/docker/overlay2/z3v309ovf8pljyonnnee2muhf/diff:/var/lib/docker/overlay2/j19ib6zi0drw8jo92arvkchld/diff:/var/lib/docker/overlay2/zrgs6cj4f92o1ijj17fnv087m/diff:/var/lib/docker/overlay2/u9jqd6cvdoxhowjchd9difhpc/diff:/var/lib/docker/overlay2/tnqygqyjrdca6y33o9e9oh0vh/diff:/var/lib/docker/overlay2/5pnfvle0ktpq9gjugxcwvgukx/diff:/var/lib/docker/overlay2/dc450aba63a0eaf7b237134228517817de49791b13b6db386f1335c63b998a13/diff:/var/lib/docker/overlay2/4254aa5a15b7a1a05ed08c2346f86df7dab96544bb8c7d56332b4fa9413bc527/diff:/var/lib/docker/overlay2/55e01baf1b861646b6db9b48cfeffe22cca0cc49524e9942641a093e7f84fae6/diff:/var/lib/docker/overlay2/8473c4891dedd6f45ceef88a0e67cb3208e0db57ad1428cdf49d3d1762c7a271/diff:/var/lib/docker/overlay2/f7993782410577c03edeca7a5e4e12372ab7aa035d47e38f4ec21597fcb1269c/diff:/var/lib/docker/overlay2/56b6e3f7631213231a7f3202c7b79133345c71615fb1966ce490cebeab5a4cc6/diff:/var/lib/docker/overlay2/49628d8edafed72f2c941dfef4d7176fdd88f2c74433290aa8e1f8cc2fac31eb/diff:/var/lib/docker/overlay2/79b9420293aa05a523bbbe151ea23ca877e7b991c3a67cc0fb31a5bb54556c59/diff",
                "MergedDir": "/var/lib/docker/overlay2/jab8z5io0qkpo746cuxz4woxc/merged",
                "UpperDir": "/var/lib/docker/overlay2/jab8z5io0qkpo746cuxz4woxc/diff",
                "WorkDir": "/var/lib/docker/overlay2/jab8z5io0qkpo746cuxz4woxc/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:6af7a54a0a0dc3d3b622e2ffb19b80c55b3e29b07857efb3d818517cad416e3b",
                "sha256:53d40515380c2dce4348df0565356261e1795bd9c68f0263fa14d0bdbf52521d",
                "sha256:eccb9ed74974c6ffbb0ffe29805839db91d2b4f4e2cdc61ee70650d6210e7fbd",
                "sha256:dcc1cfeee1ab24b1736806348df7db43070fe755d6912cba38ce80340585ec16",
                "sha256:474c7af106972488141362c55112a7419898074e526ebc62cba9de91fbac75f8",
                "sha256:b032a3b4d7f873a57ba6fcd7877e089a27e4a70a1d7da411ebf80566d80b71fc",
                "sha256:9c09c0d6f95a97ae2ea555abd3034001e5947e81b201b33af41bceb5da32b506",
                "sha256:e36b5e9d496317a4649b0701a90dd5a6f34624ffaf849235bb9a6e0bbfa41693",
                "sha256:6762c8e9a3bb4e19c123075c253d2e13b3702472988a6544b629d2fccdea752a",
                "sha256:75153e78c46c2f7f511723ab6a1fd84274e82671f90966a53c649c041490cf86",
                "sha256:d6eca2b4f6f33eddb615aea7816074ff159b9b9d46c0a5a51e1e584c17cb1cc6",
                "sha256:70e2e3fec63c3e6899310d53d4b78f88ba5a2ca55243a35097d607c137702648",
                "sha256:68104834a17a6d24cfff188596ba9ee9161c1c46cc98acdd2933007acfcafe9f",
                "sha256:e5aae9822f2b3bb9777320c40646abdf2bf834633e0bd087dec1cecc68c9977b",
                "sha256:0ebef12aa23fcac19330025976c0b23aa5c747088cf8d73f78dbbb9c816cfc6e",
                "sha256:beb133a886856f9ab5950307851d10cf6b49a4391cf491a40ebd991bef7a910d",
                "sha256:652b7df76a9c0b0360bc57fe3f2bc3d5ef24116ea14568cc4d1595e29e583e69",
                "sha256:7b1696dbb611b93f6ba787ad55eee26efb9ca20df9f1c0f98a42d5db3cd986be",
                "sha256:59cb6d1e553a22855afec2ceb3ba12d8dc9853b72f513473fe167402b4f533d1",
                "sha256:ad89da361d5c5941e51ae957f05b2e3daa5cc2f41c909c90c315e41b72cfc59e",
                "sha256:c5ecc0b5e243fc9df344498e22dec928a55b3e0c18e30f8c0702bac9a8440a8a",
                "sha256:8a3fd995f9bb55b47ffad664d3fe8de3dcc1b26419dd9459db046d78a216ca89",
                "sha256:88189ec8d0399ec008ed23f9ac926e2ac226cc6ef69047c900974d03a1ade9f7",
                "sha256:9bb79d21b13833244b139b849da01cdfbe92ff8e497aad67d06ac9373514ff7f",
                "sha256:ea42b2ddbfd6ed26e0d9c0903ea92eed24ce59d75d946f25dc523010abc18ca2",
                "sha256:94bfd162feb22b89bc4db8d954d4dc629e8451009c911705704c138469c6d835",
                "sha256:6ee3dab459fdc9f981421b6d049771db69f4df66defaf48c3de89246bc9c5d35",
                "sha256:0236b74c107f642c440a728788ce0faf647966365912a81579e5399dc30411e5",
                "sha256:e468cd88185dc876f898da11805f10d1fa5bc1a0b372e7fdccec79cdf1732634"
            ]
        },
        "Metadata": {
            "LastTagTime": "2024-03-16T07:56:54.194060634Z"
        }
    }
]
```

WSL
![图片](https://github.com/Monadical-SAS/oddslingers.poker/assets/29831189/8491076d-01cb-49a3-a921-58fb4f3ea39e)

WIN
![图片](https://github.com/Monadical-SAS/oddslingers.poker/assets/29831189/d7850fc3-2abc-4c4e-ada4-0e86c1767155)
